const markets = [
  { id:'moon', name:'MOONBERRY', symbol:'MNB', question:'Will Moonberry futures close above ₱ 86 by sundown?', price:82, end:'14:00', category:'AGRICULTURE', rumor:'A lantern-maker says the northern groves are glowing early.', probability:62, answer:72, settled:false },
  { id:'wyrm', name:'WYRM OIL', symbol:'WYR', question:'Will Wyrm Oil rise more than 8% before the bell?', price:118, end:'16:30', category:'ENERGY', rumor:'Dockhands report a warm current under the eastern piers.', probability:44, answer:31, settled:false },
  { id:'mana', name:'MANA DUST', symbol:'MND', question:'Will Mana Dust supply fall below 400 crates this week?', price:406, end:'18:00', category:'ARCANE', rumor:'The academy quartermaster has been counting empty shelves.', probability:37, answer:68, settled:false }
];
const equipment = [
  {id:'lens', name:'ORACLE LENS', icon:'◉', price:420, text:'A calibrated crystal lens. Reveals the market range and a faint signal of unusual volatility.', bought:false},
  {id:'ticker', name:'ETHER TICKER', icon:'⌁', price:760, text:'Live aether-flow readings from three city gates. Unlocks a second data source.', bought:false},
  {id:'sim', name:'FATE SIMULATOR', icon:'✦', price:1400, text:'Run thousands of possible afternoons. Calamity risk becomes measurable, never certain.', bought:false}
];
let selectedId='moon', balance=1240, ticket=1, history=[];
const $=id=>document.getElementById(id);
const tutorialSteps=[
  {target:'tutorial-markets',title:'Start with the markets.',copy:'Every shift gives you three questions about the fantasy market. Pick one to open its forecast ticket.'},
  {target:'tutorial-notes',title:'Listen before you calculate.',copy:'Rumors arrive as field notes and email. They are useful, but unsourced. Treat word of mouth as a clue, not a certainty.'},
  {target:'tutorial-ticket',title:'Price your confidence.',copy:'Move the slider to say how likely you think the outcome is. Accuracy pays more, while overconfidence makes misses hurt.'},
  {target:'tutorial-signals',title:'Buy a sharper view.',copy:'Your first forecasts use only local knowledge. Spend your winnings in Equipment to unlock charts and professional data tools.'},
  {target:'tutorial-ticket',title:'Lock it before the bell.',copy:'Submit your forecast to settle the ticket. Calamities can bend the market unexpectedly, and their faint warning signs are never guarantees.'}
];
let tutorialIndex=0;
function selected(){return markets.find(m=>m.id===selectedId)}
function endTutorial(){sessionStorage.setItem('forecast-tutorial-seen','1');$('tutorial-card').classList.add('hidden');$('tutorial-backdrop').classList.add('hidden');document.querySelectorAll('.tutorial-focus').forEach(el=>el.classList.remove('tutorial-focus'))}
function renderTutorial(){const step=tutorialSteps[tutorialIndex];document.querySelectorAll('.tutorial-focus').forEach(el=>el.classList.remove('tutorial-focus'));$(step.target).classList.add('tutorial-focus');$('tutorial-step').textContent=`${String(tutorialIndex+1).padStart(2,'0')} / ${String(tutorialSteps.length).padStart(2,'0')}`;$('tutorial-title').textContent=step.title;$('tutorial-copy').textContent=step.copy;$('tutorial-next').textContent=tutorialIndex===tutorialSteps.length-1?'BEGIN SHIFT →':'NEXT LESSON →';$('tutorial-progress').innerHTML=tutorialSteps.map((_,i)=>`<span class="${i===tutorialIndex?'current':''}"></span>`).join('')}
function startTutorial(){if(sessionStorage.getItem('forecast-tutorial-seen'))return;$('tutorial-card').classList.remove('hidden');$('tutorial-backdrop').classList.remove('hidden');renderTutorial()}
function renderMarkets(){ $('market-list').innerHTML=markets.map(m=>`<div class="market-row ${m.id===selectedId?'selected':''}" data-market="${m.id}"><div class="market-name">${m.name}<span>${m.symbol} · ₱ ${m.price}</span></div><div class="market-question">${m.question}</div><div class="market-footer"><span class="market-tag">${m.category}</span><span class="market-time">SETTLES ${m.end}</span></div></div>`).join(''); document.querySelectorAll('[data-market]').forEach(el=>el.onclick=()=>{selectedId=el.dataset.market;renderMarkets();renderForecast()})}
function renderForecast(){const m=selected(); $('selected-title').textContent=m.name; $('ticket-id').textContent=`TKT—${String(ticket).padStart(3,'0')}`; $('forecast-content').innerHTML=`<p class="forecast-prompt">${m.question}</p><div class="range-row"><span class="tiny-label">YOUR CONFIDENCE</span><strong class="range-value" id="range-value">${m.probability}%</strong></div><input id="confidence" type="range" min="5" max="95" value="${m.probability}"><div class="range-labels"><span>NO WAY</span><span>COIN FLIP</span><span>LOCKED IN</span></div><div class="intel-note"><span>✳</span><div><b>Field note</b><br>${m.rumor}</div></div><button class="submit-btn" id="submit-forecast">LOCK FORECAST →</button>`; const input=$('confidence');input.oninput=()=>{m.probability=input.value;$('range-value').textContent=`${input.value}%`};$('submit-forecast').onclick=settleForecast}
function renderFeed(){ $('feed-list').innerHTML=markets.map(m=>`<div class="feed-item"><span class="feed-time">08:${markets.indexOf(m)*7+14}</span><div class="feed-copy"><strong>${m.name}</strong><br>${m.rumor}</div><span class="source-dot"></span></div>`).join('') }
function drawChart(){const wrap=$('chart-wrap');wrap.innerHTML='<canvas id="signal-chart" width="700" height="230"></canvas>';const c=$('signal-chart'),x=c.getContext('2d'),w=c.width,h=c.height,m=selected();x.clearRect(0,0,w,h);x.strokeStyle='#e4e9e1';x.lineWidth=1;for(let i=1;i<5;i++){x.beginPath();x.moveTo(0,i*h/5);x.lineTo(w,i*h/5);x.stroke()}const pts=[];for(let i=0;i<16;i++)pts.push(45+Math.sin(i*.7)*12+i*1.4+(Math.random()*12-6));x.strokeStyle='#f47761';x.lineWidth=3;x.beginPath();pts.forEach((v,i)=>{const px=i*w/15,py=h-v*2.5;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();x.strokeStyle='#0c7775';x.lineWidth=1.5;x.setLineDash([6,5]);x.beginPath();x.moveTo(0,h-130-m.probability*.1);x.lineTo(w,h-130-m.probability*.1);x.stroke();x.setLineDash([]);x.fillStyle='#718083';x.font='11px DM Mono';x.fillText('08:00',0,h-4);x.fillText('NOW',w-30,h-4);}
function settleForecast(){const m=selected();const accuracy=100-Math.abs(Number(m.probability)-m.answer);const calamity=(m.id==='wyrm'&&Math.random()>.35)||(m.id==='mana'&&Math.random()>.68);const payout=Math.max(35,Math.round(accuracy*4.2))*(calamity?.45:1);balance+=payout;history.unshift({m,accuracy,payout,calamity});m.settled=true;ticket++;$('balance').textContent=`₱ ${balance.toLocaleString()}`;$('balance-delta').textContent=`+₱ ${Math.round(payout)} this forecast`;toast(calamity?'CALAMITY EVENT: aether shear disrupted the market.':'FORECAST SETTLED: payment posted to ledger.');drawChart();renderArchive();renderForecast()}
function renderInbox(){ $('inbox-list').innerHTML=markets.map((m,i)=>`<article class="inbox-card"><span class="feed-time">TODAY / 08:${14+i*7}</span><h3>${m.name} field report</h3><p>${m.rumor}</p><span class="inbox-source">FROM: ${['Mara, lantern-maker','Joss, dockhand','Quartermaster Pell'][i]} · UNSOURCED</span></article>`).join('') }
function renderUpgrades(){ $('upgrade-list').innerHTML=equipment.map(e=>`<article class="upgrade-card"><div class="upgrade-icon">${e.icon}</div><h3>${e.name}</h3><p>${e.text}</p><button class="buy-btn" data-buy="${e.id}" ${e.bought?'disabled':''}>${e.bought?'INSTALLED':'BUY FOR ₱ '+e.price}</button></article>`).join('');document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>buy(b.dataset.buy)) }
function buy(id){const e=equipment.find(x=>x.id===id);if(e.bought)return;if(balance<e.price){toast('INSUFFICIENT FUNDS: settle a market first.');return}balance-=e.price;e.bought=true;$('balance').textContent=`₱ ${balance.toLocaleString()}`;$('upgrade-count').textContent=equipment.filter(x=>!x.bought).length;toast(`${e.name} INSTALLED: new signal unlocked.`);renderUpgrades();drawChart()}
function renderArchive(){ $('archive-list').innerHTML=history.length?history.map(h=>`<div class="archive-row"><strong>${h.m.name}</strong><span>${h.m.question}</span><span class="${h.calamity?'loss':'win'}">${h.calamity?'CALAMITY':'SETTLED'}</span><span class="${h.calamity?'loss':'win'}">+₱ ${Math.round(h.payout)}</span></div>`).join(''):'<div class="archive-row"><strong>No settled markets</strong><span>Your first ticket is waiting.</span><span>--</span><span>--</span></div>' }
function toast(message){const t=$('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)}
function switchView(view){document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));$('desk-view').classList.toggle('hidden',view!=='desk');document.querySelectorAll('.secondary-view').forEach(v=>v.classList.add('hidden'));if(view!=='desk')$(view+'-view').classList.remove('hidden');if(view==='inbox')renderInbox();if(view==='upgrades')renderUpgrades();if(view==='archive')renderArchive()}
document.querySelectorAll('.nav-item').forEach(n=>n.onclick=()=>switchView(n.dataset.view));document.querySelectorAll('[data-view-target]').forEach(n=>n.onclick=()=>switchView(n.dataset.viewTarget));$('refresh-chart').onclick=drawChart;renderMarkets();renderForecast();renderFeed();renderArchive();setInterval(()=>{$('clock').textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',hour12:false})},1000);
$('tutorial-next').onclick=()=>{if(tutorialIndex===tutorialSteps.length-1){endTutorial();return}tutorialIndex++;renderTutorial()};$('tutorial-skip').onclick=endTutorial;startTutorial();
